# Generated by Django 4.1.3 on 2022-11-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='indiceDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('serie', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('editor', models.CharField(max_length=30)),
                ('idioma', models.CharField(max_length=30)),
                ('pag', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('formato', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
            ],
        ),
    ]
